name: build cutechess
on:
  workflow_dispatch:

jobs:
    build:
        name: "${{ matrix.os }} Qt ${{ matrix.qt_version }}"
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            qt_version: [5.15.2]
            os: [windows-latest]
        steps:
            - uses: actions/checkout@v3

            - name: install qt 6.x
              uses: jurplel/install-qt-action@v3
              if: startsWith(matrix.qt_version, '6.')
              with:
                version: ${{ matrix.qt_version }}
                modules: 'qt5compat'
                aqtversion: '==2.1.*'

            - name: build cute chess
              if: matrix.os == 'windows-latest'
              shell: cmd
              run: |
                  call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
                  mkdir build
                  cd build
                  cmake ..
                  cmake --build . --config release
                                    
            - uses: actions/upload-artifact@v3
              with:
                name: CuteChessMyRelease
                path: D:\a\CuteChess\CuteChess\build\

